MyApp/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using MyApp.Models;

using MyApp.Migrations;
using System.Net;

namespace MyApp.Controllers
{
    public class RentalsController : Controller
    {
        private ApplicationDbContext _db;
        public RentalsController()
        {
            _db = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }


        [HttpGet]
        public ActionResult New()
        {
            var rental = new Rental();
            var movie = _db.Movies.ToList();
            ViewBag.movie = movie;
            var customer = _db.Customers.ToList();
            ViewBag.customer = customer;

            return View(rental);
        }

        [HttpPost]
        public ActionResult New(Rental rental,IList<dynamic>movie)
        {
            if (ModelState.IsValid)
            {

                var BTotal = movie.Count;
                string MovieID;


                var i = 0;
                for (var Bindex = 0; Bindex < BTotal; Bindex++)
                {
                    i = i + 1;
                    MovieID = Convert.ToString(movie[Bindex]);
                    rental.MovieID = MovieID;
                    _db.Rentals.Add(rental);
                    _db.SaveChanges();

                }
                return RedirectToAction("Index");

            }

            var movieinfo = _db.Movies.ToList();
            ViewBag.movie = movieinfo;
            var customer = _db.Customers.ToList();
            ViewBag.customer = customer;

            return View(rental);


        }

        // GET: Rentals
        public ActionResult Index()
        {
            var rental = _db.Rentals.ToList();
         
            return View(rental);
        }

        public ActionResult Delete(int? id)
        {

          
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Rental rental = _db.Rentals.Find(id);
                if (rental == null)
                {
                    return HttpNotFound();
                }
                _db.Rentals.Remove(rental);
                _db.SaveChanges();
                return RedirectToAction("Index");

           

        }

    }
}

MyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#002E62;font-weight:bold;font-size:16px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MyApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New Rental", "Index", "Rentals")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="background-color:#002E62;color:white;width:150px;padding-left:13px; border-radius:3px;">&copy; @DateTime.Now.ToShortTimeString() - My App</p>
        </footer>
    </div>

  
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

MyApp/Views/Shared/partial_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#ED0050;font-weight:bold;font-size:16px;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MyApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New Rental", "New", "Rentals")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="background-color:#ED0050;color:white;width:150px;padding-left:13px; border-radius:3px;">&copy; @DateTime.Now.ToShortTimeString() - My App</p>
        </footer>
    </div>

  
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>